name: Unit tests without external tools

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        python-version: ['3.11', '3.12']
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: test
        auto-activate-base: false
    - name: Install epytope
      shell: bash -el {0}
      run: |
        pip install .
    - name: Install Test dependencies
      shell: bash -el {0}
      run: |
        pip install pytest
        conda install -c conda-forge glpk
    - name: Run Tests
      shell: bash -el {0}
      run: pytest epytope/test/ --ignore=epytope/test/external -v
